#!/usr/bin/env python3

import skilstak.colors as c
import sys

def The_Dark_Ages(answer):
    print(c.clear + c.red + 'Your soul will go to the orcs of the East, your memories will go to the goblins of the South, and your body will go as food to the trolls of the North. Say hello to your nightmares.' + c.reset)
    if answer == "why?":
        print(c.blue + 'Because I hate you and I am evil. Thats why!')
        The_Dark_Side_Shall_Rise_And_Destroy_The_Jedi()

def The_Dark_Side_Shall_Rise_And_Destroy_The_Jedi():
    print(c.yellow + "hello nightmares" + c.reset)

if __name__ == '__main__':
    if len(sys.argv) > 1:
        The_Dark_Ages(sys.argv[1])
    else:
        The_Dark_Ages("blah")
